kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc
  namespace: storage
spec:
  storageClassName: localdisk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

