apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: storage
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox
      command: ['sh','-c','echo Success >/output/log']
      volumeMounts: 
      - name: pv-storage
        mountPath: /output/
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: my-pvc

